course_registration/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  get '/students/smartest', :to => 'students#smartest'

  resources :students do
    resources :grades
  end

  resources :users, only: [:show]

  root to: 'application#home'

  end

course_registration/app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :user
  belongs_to :student

  validates :behavior, presence: true
  validates :score, presence: true

  def self.smartest_students
    order('score desc').first(3)
  end

end

course_registration/app/controllers/grades_controller.rb
class GradesController < ApplicationController

  def index
    @student = Student.find_by_id(params[:student_id])
    @grades = Grade.all
  end

  def show
  end

  def new
  @student = Student.find_by_id(params[:student_id])
  @grade = @student.grades.build
  end

  def create
    @grade = current_user.grades.build(grade_params)
    @grade.student = Student.find_by_id(params[:student_id])
    if @grade.save
      redirect_to students_path
    else
      render :new
    end
  end

  def edit
    @grade = Grade.find(params[:id])
end

  def update
    @url = student_grade_path
    @grade = Grade.find(params[:id])
    if @grade.user_id = current_user.id
      @grade.update_attributes(grade_params)
      @grade.save
      redirect_to students_path
    else
      @grade.errors.add(:base, "You must be the original creator to make changes
      to this grade.")
      render :edit
    end
  end

  private

  def grade_params
    params.require(:grade).permit(:student_id, :user_id, :score, :behavior)
  end

  def set_grade
    @grade = Grade.find(params[:id])
  end

end

course_registration/app/views/grades/_form.html.erb
<% if @grade.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@grade.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
    <% @grade.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </div>
<% end %><br>

<%= form_for @grade, url: "/students/#{@grade.student_id}/grades/#{@grade.id}" do |f| %>

  <%= f.label :behavior %>
  <%= f.text_field :behavior %><br>

  <%= f.label :score %>
  <%= f.number_field :score, min: 0, max: 100 %><br>

  <%= f.submit %>
  <% end %>

course_registration/app/views/grades/edit.html.erb
<div class="student-body">
  <h1>UPDATE GRADE</h1><br>
  <%= render 'form' %>
</div>

course_registration/app/views/grades/index.html.erb
<div class="student-body">
  <h1>STUDENT GRADES</h1>
    <%= @student.first_name %> <%= @student.last_name%><br>
  <div class="student-card">
        <% @student.grades.each do |grade| %>
      Behavior: <%= grade.behavior %><br>
      Score: <%= grade.score %><br>
      <% if current_user == grade.user %>
        <%= link_to 'Update Grade', edit_student_grade_path(@student, grade) %><br>
        Submitted by: <%= grade.user.email %>
        <% else %>
        Submitted by: <%= grade.user.email %>
      <% end %>
<% end %>
<br>
<%= link_to "Add a Grade for #{@student.first_name}", new_student_grade_path(@student) %>
</div>
<div class="student-links">
  <%= link_to "Back to All Students", students_path %>
</div>

course_registration/app/views/grades/new.html.erb
<div class="student-body">
  <h1>ADD A NEW GRADE</h1>
<%= render 'form' %>
<div class="student-links">
  <%= link_to "Back to All Students", students_path %>
</div>
</div>