course_registration/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  get '/students/smartest', :to => 'students#smartest'

  resources :students do
    resources :grades
  end

  resources :users, only: [:show]

  root to: 'application#home'

  end

course_registration/app/models/student.rb
class Student < ActiveRecord::Base
  has_many :grades
  has_many :users, through: :grades

  validates :first_name, presence: true
  validates :last_name, presence: true



end

course_registration/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
      @students = Student.all
      @grades = current_user.grades.all
  end

  def show
    @student = Student.find_by_id(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = current_user.students.build(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find_by_id(params[:id])
  end

  def update

  end

  def destroy

  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name)
  end


end

course_registration/app/helpers/students_helper.rb
module StudentsHelper
end

course_registration/app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@student.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @student do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>

  <%= f.submit %>
  <% end %>

course_registration/app/views/students/index.html.erb
<div class="student-body">
  <h1>All Flatiron High School Students</h1>
  <div class="student-card">
  <% @students.each do |student| %>
  <%= student.first_name %> <%= student.last_name%><br>
  <div class="grade-links">
  <%= link_to "View #{student.first_name}'s Grades", student_grades_path(student) %><br>
  <%= link_to "Add New Grade for #{student.first_name}", new_student_grade_path(student) %>
  </div>
<% end %>
</div>

<div class="student-links">
  <%= link_to "Enroll a New Student", new_student_path %><br>
  <%= link_to "Top 3 Students", students_smartest_path %>
</div>

</div>

course_registration/app/views/students/new.html.erb
<div class="student-body">
  <h1>Enroll a New Student</h1><br>
<%= render 'form' %>

<div class="student-links">
  <%= link_to "Back to All Students", students_path %>
</div>

</div>

course_registration/app/views/students/show.html.erb
<div class="student-body">
  <h1>STUDENT PROFILE</h1><br>

<div class="student-card">
  <%= @student.first_name %> <%= @student.last_name %>
  <% if @student.grades.nil? %>
No grades available for <%= @student.first_name %> <%= @student.last_name %>.<br>
    <%= link_to "Add Grades for #{@student.first_name}", new_student_grade_path(@student) %>
  <% else %>
  <%= link_to "View #{@student.first_name}'s Grades", student_grades_path(@student) %>
      <% end %>
</div>

<br>
<div class="student-links">
  <%= link_to "Enroll a New Student", new_student_path %><br>
  <%= link_to "Back to All Students", students_path %>
</div>
</div>

course_registration/app/views/students/smartest.html.erb
<div class="student-body">
  <h1>TOP OF THE CLASS</h1><br>

  <div class="student-card">
    <% @grades = Grade.smartest_students %>
    <% @grades.each do |grade| %>
    <p><%= grade.student.first_name %> <%= grade.student.last_name %><br>
      <%= grade.score %> - <%= grade.behavior %></p>
  <% end %>
</div>
  <div class="student-links">
    <%= link_to "Back to All Students", students_path %>
  </div>
</div>